namespace SuperMetroidRandomizer;

internal enum ItemID : ushort
{
    EnergyTank = 0xEED7,
    Missile = 0xEEDB,
    SuperMissile = 0xEEDF,
    PowerBomb = 0xEEE3,
    Bombs = 0xEEE7,
    ChargeBeam = 0xEEEB,
    IceBeam = 0xEEEF,
    HighJump = 0xEEF3,
    SpeedBooster = 0xEEF7,
    WaveBeam = 0xEEFB,
    SpazerBeam = 0xEEFF,
    SpringBall = 0xEF03,
    VariaSuit = 0xEF07,
    GravitySuit = 0xEF0B,
    XRayScope = 0xEF0F,
    PlasmaBeam = 0xEF13,
    GrappleBeam = 0xEF17,
    SpaceJump = 0xEF1B,
    ScrewAttack = 0xEF1F,
    MorphBall = 0xEF23,
    ReserveTank = 0xEF27,

    EnergyTank_ChozoBall = 0xEF2B,
    Missile_ChozoBall = 0xEF2F,
    SuperMissile_ChozoBall = 0xEF33,
    PowerBomb_ChozoBall = 0xEF37,
    Bombs_ChozoBall = 0xEF3B,
    ChargeBeam_ChozoBall = 0xEF3F,
    IceBeam_ChozoBall = 0xEF43,
    HighJump_ChozoBall = 0xEF47,
    SpeedBooster_ChozoBall = 0xEF4B,
    WaveBeam_ChozoBall = 0xEF4F,
    SpazerBeam_ChozoBall = 0xEF53,
    SpringBall_ChozoBall = 0xEF57,
    VariaSuit_ChozoBall = 0xEF5B,
    GravitySuit_ChozoBall = 0xEF5F,
    XRayScope_ChozoBall = 0xEF63,
    PlasmaBeam_ChozoBall = 0xEF67,
    GrappleBeam_ChozoBall = 0xEF6B,
    SpaceJump_ChozoBall = 0xEF6F,
    ScrewAttack_ChozoBall = 0xEF73,
    MorphBall_ChozoBall = 0xEF77,
    ReserveTank_ChozoBall = 0xEF7B,
}